name: Terraform PR Plan

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    name: Terraform DEV Plan
    runs-on: ubuntu-latest

    environment: dev

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_wrapper: false

      - name: Prepare and Validate SSH Public Key
        shell: bash
        run: |
          set -euo pipefail

          mkdir -p "$HOME/.ssh"

          cp keys/finops_vm.pub "$HOME/.ssh/finops_vm.pub"

          chmod 600 "$HOME/.ssh/finops_vm.pub"

          echo "Validating SSH public key..."

          ssh-keygen -l -f "$HOME/.ssh/finops_vm.pub"

          echo "SSH public key validation successful."

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Azure Login with OIDC
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Verify Azure Authentication
        run: |
          az account show \
            --query "{Subscription:name,Tenant:tenantId}" \
            --output table

      - name: Terraform Init
        working-directory: environments/dev
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: environments/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: environments/dev
        run: |
          terraform plan \
            -input=false \
            -no-color \
            -var-file=ci.tfvars